### ISSUE TITLE
manage.py runserver crashing Python

### ISSUE THREAD

**Issue by mbrpistoni** [casparluc/VikingDoom#2]
I have my database configured and populated through manage.py. Now I'm trying to run the server using manage.py runserver. This makes my Python crash. 
I loaded the project on PyCharm to see what's going on and, the only error it shows, is this:
**Process finished with exit code -1073741819 (0xC0000005)**

I can't find the reason why this is happening. So far, the only clue is someone commenting somewhere that this might be an access denied error  (https://forum.qt.io/topic/9839/error-quot-during-startup-program-exited-with-code-0xc0000005-quot)

Also, the other manage.py subcommands are working. 
Am I forgetting come config file somewhere?

**Comment by davinellulinvega** [comment]
Hello,

Since you are using Pycharm to try and debug the project, could it be that you are encountering the error described here: https://stackoverflow.com/questions/41034361/pycharm-django-project-fails-to-run-with-debugging and here: https://code.djangoproject.com/ticket/27586?
A work around is suggested on both pages.

Do you have a traceback of the original error that made your python crash by simply running manage.py (without PyCharm)?

Sincerely.

**Comment by mbrpistoni** [comment]
Hi! 
I will look for the traceback as soon as I come back from work. 
Also I will try the workaround to see if I can finally debug the app. 
Thanks!

**Comment by mbrpistoni** [comment]
Hi!

traceback of the error:

Faulting application name: python.exe, version: 3.6.150.1013, time stamp: 0x585cd094
Faulting module name: ucrtbase.dll, version: 10.0.14393.0, time stamp: 0x57898db2
Exception code: 0xc0000005
Fault offset: 0x0003bd9e
Faulting process id: 0x274c
Faulting application start time: 0x01d29c2a5d595c08
Faulting application path: C:\Python36\python.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: 279ccb86-cfc8-46ff-a033-ec192d82431d
Faulting package full name: 
Faulting package-relative application ID: 

doing the workaround you linked me works, but only in PyCharm. I don't know how or where I should add that environment variable (the one I'm adding in PyCharm) to make it work during normal execution.
I was thinking in adding it in the Django settings.py, but it would never work because of it's syntax 
**=C; = c:\"**

Any suggestions (apart from moving to linux, I want to code my bots in c++ using visual studio)?

**Comment by mbrpistoni** [comment]
Ok, I found a solution digging into the django forum. 
The problem affects only to Windows 10 and only because the auto reloader (I guess this happens at some point when calling ucrtbase.dll, which is exclusive of Windows 10)
To make it work you need to run **manage.py runserver --noreload**
Will see if that gives me any problems when asking for the json's etc...

This where I found the solution
[https://code.djangoproject.com/ticket/27766](url)

Cheers

**Comment by davinellulinvega** [comment]
Hello,

Glad to hear that it all worked out in the end for you.
On my side, I have just finished to install windows 7 on my computer to try and go through the installation process.
I noticed that you will probably face another problem, in the near future, related to Thespian. While I was developing the game engine for Viking Doom, I came across a bug in the Thespian framework, which has been solved in a branch of the thespian project on github and was released until last week. The solution implemented apparently introduced another bug and so the developer had to rollback his modifications. This means that for you to be able to use the game engine on your machine, you will have to uninstall your current version and reinstall thespian from its source code: https://github.com/godaddy/Thespian.git, using the **add_system_private** branch.

Sincerely.

**Comment by mbrpistoni** [comment]
ufff ok...
Please, add all this to the documentation. Spare the pain to the future generations XD
Will come back if anything else fails. 
Cheers

**Comment by davinellulinvega** [comment]
Well the pain should have been avoided for you already, if it was not for this rollback.
Anyway, I will add a temporary note in the doc.

Sincerely.

**Comment by davinellulinvega** [comment]
Hello,

To install Thespian from the repository on Windows, you can simply download the zip file of the `add_system_private` branch. Extract the content and launch the `setup.py install` script included in the folder. On windows 7 it worked well and I was able to run the whole project.
Last but not least, I fixed some errors that are related to running the project from Pycharm on windows, so you might want to make sure you have the latest version.

Sincerely.
