### ISSUE TITLE
Create game json incorrectly escaped

### ISSUE THREAD

**Issue by OrangyTang** [casparluc/VikingDoom#5]
The response from the create game PUT request seems to be returning json with the quote characters incorrectly escaped. The following is captured from wireshark:

http://imgur.com/a/rHYkF

As you can see, there's an incorrect leading and trailing double quote character, and all double quote characters are escaped. Since we're sending and receiving raw text, these should not be escaped at this point. I suspect the server is running the output through an escaping method twice somehow.

Thanks

**Comment by davinellulinvega** [comment]
Hello,

Thank you very much for your feedback.
I will have a look at this issue as soon as possible.

Sincerely.

**Comment by davinellulinvega** [comment]
Hello,

Sorry for the long wait.
The problem has been identified and a solution implemented.
A new version of the game engine is now running on the server and should send back a correctly formatted json response.
Could you confirm that you are receiving messages in a correct format, before closing the issue?

Sincerely.

**Comment by OrangyTang** [comment]
Hello,
I tried to test this just now to see if it is fixed, but am getting 500 internal server errors from the game create url.

**Comment by davinellulinvega** [comment]
Hello,
 
The new game url should be back in action now, but I will have to reboot the server later this night to introduce a new mechanism for tracking players that quit before the beginning of a game.

Sincerely.

**Comment by OrangyTang** [comment]
Still seeing 500 errors here - although for submitting a turn this time, so not sure if it's the same issue or something else. Does this request look correct? A more useful error code other than just 500 and no description would be good.

![image](https://cloud.githubusercontent.com/assets/4281392/24023216/a9ead708-0aa2-11e7-8e49-2d66357005fa.png)

Thanks

**Comment by davinellulinvega** [comment]
Hello,

I have added a clearer message to the error.
However, concerning your request, it seems that django is unable to parse the payload attached to your request.
What library / program are you using for making calls to the server?

Sincerely.

**Comment by OrangyTang** [comment]
I'm using UnityWebRequest ( https://docs.unity3d.com/Manual/UnityWebRequest.html ) for the actual http, which is based on cUrl. The json is hand-crafted though since it's so minimal.

Do you know whether the error is in parsing the actual http request, or in parsing the json? Will probably try a side by side comparison with the python bot this evening and see if I can spot anything.

**Comment by davinellulinvega** [comment]
Hello,

The error is in parsing the http request. However, as stated in the [docs](http://vikingdoom.com/docs/) page, the **POST** request is not formatted in json. Instead, the **action** and **code** should be send as standard variables.
If you are using UnityWebRequest, something along the following lines should yield a positive result:
```
List<IMultipartFormSection> formData = new List<IMultipartFormSection>();
formData.Add( new MultipartFormDataSection("code=your_code&action=your_next_action") );

UnityWebRequest www = UnityWebRequest.Post("http://www.vikingdoom.com/play/game_code/", formData);
yield return www.Send();
```
(Example adapted from [here](https://docs.unity3d.com/Manual/UnityWebRequest-SendingForm.html)).
I am quite sorry, but i am no expert when it comes to Unity. However, I think you do understand what I am pointing at in this case. It seems that the error is in how you format and send the data/payload to the server through the **POST** request.

Sincerely.

**Comment by OrangyTang** [comment]
Ah, you mean they should be form encoded?

That makes sense. The docs only say 'in the request body' so it's ambiguous about the actual encoding, it would be good to clarify that maybe. Will give it a try tonight and close this issue!

Thanks.

**Comment by OrangyTang** [comment]
I tried to test this today, however the start game / PUT request is returning 500 errors. Is the server down again?

**Comment by davinellulinvega** [comment]
Hello,

The server is running at the moment.
I have added some logs to see what the problem you are encountering is.

Sincerely.

**Comment by OrangyTang** [comment]
Have managed to successfully submit  both a start game and a few turns, seems fixed, thanks.

**Comment by davinellulinvega** [comment]
Hello,

Glad to hear that you can finally join the game.
Sorry for any inconveniences along the way.

Sincerely.
